# Generated by Django 5.1.2 on 2024-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_integrantes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familia',
                'managed': False,
            },
        ),
    ]
