# Generated by Django 5.1.2 on 2024-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tareas/')),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
    ]
